<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionsSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->delete();
        DB::table('permissions')->insert([
            0 => array(
                'id' => 1,
                'name' => 'admin.access',
                'display_name' => 'Access Admin',
                'description' => 'Required in order to access any admin area page.',
                'group' => 'admin',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            1 => array(
                'id' => 2,
                'name' => 'appearance.update',
                'display_name' => 'Update Appearance',
                'description' => 'Allows access to appearance editor.',
                'group' => 'admin',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            2 => array(
                'id' => 3,
                'name' => 'admin',
                'display_name' => 'Super Admin',
                'description' => 'Give all permissions to user.',
                'group' => 'admin',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            3 => array(
                'id' => 4,
                'name' => 'api.access',
                'display_name' => 'Access Api',
                'description' => 'Allow users to use the API and access API section in their account settings page.',
                'group' => 'api',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            4 => array(
                'id' => 5,
                'name' => 'roles.view',
                'display_name' => 'View Roles',
                'description' => 'Allow viewing ALL roles, regardless of who is the owner.',
                'group' => 'roles',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            5 => array(
                'id' => 6,
                'name' => 'roles.create',
                'display_name' => 'Create Roles',
                'description' => 'Allow creating new roles, regardless of who is the owner.',
                'group' => 'roles',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            6 => array(
                'id' => 7,
                'name' => 'roles.update',
                'display_name' => 'Update Roles',
                'description' => 'Allow updating ALL roles, regardless of who is the owner.',
                'group' => 'roles',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            7 => array(
                'id' => 8,
                'name' => 'roles.delete',
                'display_name' => 'Delete Roles',
                'description' => 'Allow deleting ALL roles, regardless of who is the owner.',
                'group' => 'roles',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            8 => array(
                'id' => 9,
                'name' => 'custom_pages.view',
                'display_name' => 'View Custom Pages',
                'description' => 'Allow viewing of all pages on the site, regardless of who created them. User can view their own pages without this permission.',
                'group' => 'custom_pages',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            9 => array(
                'id' => 10,
                'name' => 'custom_pages.create',
                'display_name' => 'Create Custom Pages',
                'description' => 'Allow creating new custom pages, regardless of who is the owner.',
                'group' => 'custom_pages',
                'restrictions' => '[{"name":"count","type":"number","description":"Maximum number of pages user will be able to create. Leave empty for unlimited."}]',
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            10 => array(
                'id' => 11,
                'name' => 'custom_pages.update',
                'display_name' => 'Update Custom Pages',
                'description' => 'Allow editing of all pages on the site, regardless of who created them. User can edit their own pages without this permission.',
                'group' => 'custom_pages',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            11 => array(
                'id' => 12,
                'name' => 'custom_pages.delete',
                'display_name' => 'Delete Custom Pages',
                'description' => 'Allow deleting of all pages on the site, regardless of who created them. User can delete their own pages without this permission.',
                'group' => 'custom_pages',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            12 => array(
                'id' => 13,
                'name' => 'custom_domains.view',
                'display_name' => 'View Custom Domains',
                'description' => 'Allow viewing all domains on the site, regardless of who created them. User can view their own domains without this permission.',
                'group' => 'custom_domains',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            13 => array(
                'id' => 14,
                'name' => 'custom_domains.create',
                'display_name' => 'Create Custom Domains',
                'description' => 'Allow user to connect their own custom domains.',
                'group' => 'custom_domains',
                'restrictions' => '[{"name":"count","type":"number","description":"Maximum number of domains user will be able to create. Leave empty for unlimited."}]',
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            14 => array(
                'id' => 15,
                'name' => 'custom_domains.update',
                'display_name' => 'Update Custom Domains',
                'description' => 'Allow editing all domains on the site, regardless of who created them. User can edit their own domains without this permission.',
                'group' => 'custom_domains',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            15 => array(
                'id' => 16,
                'name' => 'custom_domains.delete',
                'display_name' => 'Delete Custom Domains',
                'description' => 'Allow deleting all domains on the site, regardless of who created them. User can delete their own domains without this permission.',
                'group' => 'custom_domains',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            16 => array(
                'id' => 17,
                'name' => 'files.view',
                'display_name' => 'View Files',
                'description' => 'Allow viewing all uploaded files on the site. Users can view their own uploads without this permission.',
                'group' => 'files',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            17 => array(
                'id' => 18,
                'name' => 'files.create',
                'display_name' => 'Create Files',
                'description' => 'Allow uploading files on the site. This permission is used by any page where it is possible for user to upload files.',
                'group' => 'files',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            18 => array(
                'id' => 19,
                'name' => 'files.update',
                'display_name' => 'Update Files',
                'description' => 'Allow editing all uploaded files on the site. Users can edit their own uploads without this permission.',
                'group' => 'files',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            19 => array(
                'id' => 20,
                'name' => 'files.delete',
                'display_name' => 'Delete Files',
                'description' => 'Allow deleting all uploaded files on the site. Users can delete their own uploads (where applicable) without this permission.',
                'group' => 'files',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            20 => array(
                'id' => 21,
                'name' => 'files.download',
                'display_name' => 'Download Files',
                'description' => 'Allow downloading all uploaded files on the site. Users can download their own uploads (where applicable) without this permission.',
                'group' => 'files',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            21 => array(
                'id' => 22,
                'name' => 'users.view',
                'display_name' => 'View Users',
                'description' => 'Allow viewing user profile pages on the site. User can view their own profile without this permission.',
                'group' => 'users',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            22 => array(
                'id' => 23,
                'name' => 'users.create',
                'display_name' => 'Create Users',
                'description' => 'Allow creating users from admin area. Users can register for new accounts without this permission. Registration can be disabled from settings page.',
                'group' => 'users',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            23 => array(
                'id' => 24,
                'name' => 'users.update',
                'display_name' => 'Update Users',
                'description' => 'Allow editing details of any user on the site. User can edit their own details without this permission.',
                'group' => 'users',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            24 => array(
                'id' => 25,
                'name' => 'users.delete',
                'display_name' => 'Delete Users',
                'description' => 'Allow deleting any user on the site. User can request deletion of their own account without this permission.',
                'group' => 'users',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            25 => array(
                'id' => 26,
                'name' => 'localizations.view',
                'display_name' => 'View Localizations',
                'description' => 'Allow viewing ALL localizations, regardless of who is the owner.',
                'group' => 'localizations',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            26 => array(
                'id' => 27,
                'name' => 'localizations.create',
                'display_name' => 'Create Localizations',
                'description' => 'Allow creating new localizations, regardless of who is the owner.',
                'group' => 'localizations',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            27 => array(
                'id' => 28,
                'name' => 'localizations.update',
                'display_name' => 'Update Localizations',
                'description' => 'Allow updating ALL localizations, regardless of who is the owner.',
                'group' => 'localizations',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            28 => array(
                'id' => 29,
                'name' => 'localizations.delete',
                'display_name' => 'Delete Localizations',
                'description' => 'Allow deleting ALL localizations, regardless of who is the owner.',
                'group' => 'localizations',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            29 => array(
                'id' => 30,
                'name' => 'settings.view',
                'display_name' => 'View Settings',
                'description' => 'Allow viewing ALL settings, regardless of who is the owner.',
                'group' => 'settings',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            30 => array(
                'id' => 31,
                'name' => 'settings.update',
                'display_name' => 'Update Settings',
                'description' => 'Allow updating ALL settings, regardless of who is the owner.',
                'group' => 'settings',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            31 => array(
                'id' => 32,
                'name' => 'plans.view',
                'display_name' => 'View Plans',
                'description' => 'Allow viewing ALL plans, regardless of who is the owner.',
                'group' => 'plans',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            32 => array(
                'id' => 33,
                'name' => 'plans.create',
                'display_name' => 'Create Plans',
                'description' => 'Allow creating new plans, regardless of who is the owner.',
                'group' => 'plans',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            33 => array(
                'id' => 34,
                'name' => 'plans.update',
                'display_name' => 'Update Plans',
                'description' => 'Allow updating ALL plans, regardless of who is the owner.',
                'group' => 'plans',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            34 => array(
                'id' => 35,
                'name' => 'plans.delete',
                'display_name' => 'Delete Plans',
                'description' => 'Allow deleting ALL plans, regardless of who is the owner.',
                'group' => 'plans',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            35 => array(
                'id' => 36,
                'name' => 'invoices.view',
                'display_name' => 'View Invoices',
                'description' => 'Allow viewing ALL invoices, regardless of who is the owner.',
                'group' => 'invoices',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            36 => array(
                'id' => 37,
                'name' => 'tags.view',
                'display_name' => 'View Tags',
                'description' => 'Allow viewing ALL tags, regardless of who is the owner.',
                'group' => 'tags',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            37 => array(
                'id' => 38,
                'name' => 'tags.create',
                'display_name' => 'Create Tags',
                'description' => 'Allow creating new tags, regardless of who is the owner.',
                'group' => 'tags',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            38 => array(
                'id' => 39,
                'name' => 'tags.update',
                'display_name' => 'Update Tags',
                'description' => 'Allow updating ALL tags, regardless of who is the owner.',
                'group' => 'tags',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            39 => array(
                'id' => 40,
                'name' => 'tags.delete',
                'display_name' => 'Delete Tags',
                'description' => 'Allow deleting ALL tags, regardless of who is the owner.',
                'group' => 'tags',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            40 => array(
                'id' => 41,
                'name' => 'workspaces.view',
                'display_name' => 'View Workspaces',
                'description' => 'Allow viewing ALL workspaces, regardless of who is the owner.',
                'group' => 'workspaces',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            41 => array(
                'id' => 42,
                'name' => 'workspaces.create',
                'display_name' => 'Create Workspaces',
                'description' => 'Allow creating new workspaces, regardless of who is the owner.',
                'group' => 'workspaces',
                'restrictions' => '[{"name":"count","type":"number","description":"Maximum number of workspaces user will be able to create. Leave empty for unlimited."},{"name":"member_count","type":"number","description":"Maximum number of members workspace is allowed to have."}]',
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            42 => array(
                'id' => 43,
                'name' => 'workspaces.update',
                'display_name' => 'Update Workspaces',
                'description' => 'Allow updating ALL workspaces, regardless of who is the owner.',
                'group' => 'workspaces',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            43 => array(
                'id' => 44,
                'name' => 'workspaces.delete',
                'display_name' => 'Delete Workspaces',
                'description' => 'Allow deleting ALL workspaces, regardless of who is the owner.',
                'group' => 'workspaces',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            44 => array(
                'id' => 45,
                'name' => 'workspace_members.invite',
                'display_name' => 'Invite Members',
                'description' => 'Allow user to invite new members into a workspace.',
                'group' => 'workspace_members',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'workspace',
                'advanced' => 0,
            ),
            45 => array(
                'id' => 46,
                'name' => 'workspace_members.update',
                'display_name' => 'Update Members',
                'description' => 'Allow user to change role of other members.',
                'group' => 'workspace_members',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'workspace',
                'advanced' => 0,
            ),
            46 => array(
                'id' => 47,
                'name' => 'workspace_members.delete',
                'display_name' => 'Delete Members',
                'description' => 'Allow user to remove members from workspace.',
                'group' => 'workspace_members',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'workspace',
                'advanced' => 0,
            ),
            47 => array(
                'id' => 48,
                'name' => 'music.view',
                'display_name' => 'View Music',
                'description' => 'Allows viewing of music content on the site (tracks, albums, artists, channels etc.)',
                'group' => 'music',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            48 => array(
                'id' => 49,
                'name' => 'music.play',
                'display_name' => 'Play Music',
                'description' => 'Allows playback of music and video on the site.',
                'group' => 'music',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            49 => array(
                'id' => 50,
                'name' => 'music.download',
                'display_name' => 'Download Music',
                'description' => 'Allows download of music and video on the site.',
                'group' => 'music',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            50 => array(
                'id' => 51,
                'name' => 'music.embed',
                'display_name' => 'Embed Music',
                'description' => 'Allows embedding of tracks, albums and playlists on external sites.',
                'group' => 'music',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            51 => array(
                'id' => 52,
                'name' => 'music.create',
                'display_name' => 'Create Music',
                'description' => 'Allows uploading and creating new tracks and albums on the site.',
                'group' => 'music',
                'restrictions' => '[{"name":"minutes","type":"number","description":"How many minutes all user tracks are allowed to take up. Leave empty for unlimited."},{"name":"artist_selection","type":"bool","description":"Allows attaching track or album to any artist that exists on the site, instead of only the ones managed by current user."}]',
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            52 => array(
                'id' => 53,
                'name' => 'music.update',
                'display_name' => 'Update Music',
                'description' => 'Allows editing all media (album, track, artist etc.) on the site, even if user did not create them initially. User can edit their own media without this permission.',
                'group' => 'music',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            53 => array(
                'id' => 54,
                'name' => 'music.delete',
                'display_name' => 'Delete Music',
                'description' => 'Allows deleting any media item on the site, even if user did not create them initially. User can delete their own media without this permission.',
                'group' => 'music',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            54 => array(
                'id' => 55,
                'name' => 'playlists.view',
                'display_name' => 'View Playlists',
                'description' => 'Allow viewing and searching for playlists marked as public.',
                'group' => 'playlists',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            55 => array(
                'id' => 56,
                'name' => 'playlists.create',
                'display_name' => 'Create Playlists',
                'description' => 'Allow creating new playlists.',
                'group' => 'playlists',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            56 => array(
                'id' => 57,
                'name' => 'playlists.update',
                'display_name' => 'Update Playlists',
                'description' => 'Allow editing of all playlists, whether user is the owner or not. User can edit their own playlists without this permission.',
                'group' => 'playlists',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            57 => array(
                'id' => 58,
                'name' => 'playlists.delete',
                'display_name' => 'Delete Playlists',
                'description' => 'Allow deleting any playlist, whether user is the owner or not. User can delete their own playlists without this permission.',
                'group' => 'playlists',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            58 => array(
                'id' => 59,
                'name' => 'comments.view',
                'display_name' => 'View Comments',
                'description' => 'Allow viewing a single comment or list of comments on the site.',
                'group' => 'comments',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            59 => array(
                'id' => 60,
                'name' => 'comments.create',
                'display_name' => 'Create Comments',
                'description' => 'Allow creating new comments.',
                'group' => 'comments',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            60 => array(
                'id' => 61,
                'name' => 'comments.update',
                'display_name' => 'Update Comments',
                'description' => 'Allow editing of all comments, whether user created that comment or not. User can edit their own comments without this permission.',
                'group' => 'comments',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            61 => array(
                'id' => 62,
                'name' => 'comments.delete',
                'display_name' => 'Delete Comments',
                'description' => 'Allow deleting any comment, whether user created that comment or not. User can delete their own comments without this permission.',
                'group' => 'comments',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 0,
            ),
            62 => array(
                'id' => 63,
                'name' => 'artists.view',
                'display_name' => 'View Artists',
                'description' => 'Allow viewing artist page and searching for artists.',
                'group' => 'artists',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            63 => array(
                'id' => 64,
                'name' => 'artists.create',
                'display_name' => 'Create Artists',
                'description' => 'Allow creating new artists.',
                'group' => 'artists',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            64 => array(
                'id' => 65,
                'name' => 'artists.update',
                'display_name' => 'Update Artists',
                'description' => 'Allow editing of all artists, whether user has created them or not.',
                'group' => 'artists',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            65 => array(
                'id' => 66,
                'name' => 'artists.delete',
                'display_name' => 'Delete Artists',
                'description' => 'Allow deleting any artist, whether user has created them or not.',
                'group' => 'artists',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            66 => array(
                'id' => 67,
                'name' => 'albums.view',
                'display_name' => 'View Albums',
                'description' => 'Allow viewing album pages and searching for albums.',
                'group' => 'albums',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            67 => array(
                'id' => 68,
                'name' => 'albums.create',
                'display_name' => 'Create Albums',
                'description' => 'Allow creating new albums.',
                'group' => 'albums',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            68 => array(
                'id' => 69,
                'name' => 'albums.update',
                'display_name' => 'Update Albums',
                'description' => 'Allow editing of all albums, whether user has created them or not.',
                'group' => 'albums',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            69 => array(
                'id' => 70,
                'name' => 'albums.delete',
                'display_name' => 'Delete Albums',
                'description' => 'Allow deleting any album, whether user has created them or not.',
                'group' => 'albums',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            70 => array(
                'id' => 71,
                'name' => 'tracks.view',
                'display_name' => 'View Tracks',
                'description' => 'Allow viewing track page and searching for tracks.',
                'group' => 'tracks',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:52',
                'updated_at' => '2024-04-11 19:24:52',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            71 => array(
                'id' => 72,
                'name' => 'tracks.create',
                'display_name' => 'Create Tracks',
                'description' => 'Allow creating new tracks.',
                'group' => 'tracks',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:53',
                'updated_at' => '2024-04-11 19:24:53',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            72 => array(
                'id' => 73,
                'name' => 'tracks.update',
                'display_name' => 'Update Tracks',
                'description' => 'Allow editing of all tracks, whether user has created them or not.',
                'group' => 'tracks',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:53',
                'updated_at' => '2024-04-11 19:24:53',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            73 => array(
                'id' => 74,
                'name' => 'tracks.delete',
                'display_name' => 'Delete Tracks',
                'description' => 'Allow deleting any track, whether user has created them or not.',
                'group' => 'tracks',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:53',
                'updated_at' => '2024-04-11 19:24:53',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            74 => array(
                'id' => 75,
                'name' => 'genres.view',
                'display_name' => 'View Genres',
                'description' => 'Allow viewing genre pages and searching for genres.',
                'group' => 'genres',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:53',
                'updated_at' => '2024-04-11 19:24:53',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            75 => array(
                'id' => 76,
                'name' => 'genres.create',
                'display_name' => 'Create Genres',
                'description' => 'Allow creating new genres.',
                'group' => 'genres',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:53',
                'updated_at' => '2024-04-11 19:24:53',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            76 => array(
                'id' => 77,
                'name' => 'genres.update',
                'display_name' => 'Update Genres',
                'description' => 'Allow editing of all genres, whether user has created them or not.',
                'group' => 'genres',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:53',
                'updated_at' => '2024-04-11 19:24:53',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            77 => array(
                'id' => 78,
                'name' => 'genres.delete',
                'display_name' => 'Delete Genres',
                'description' => 'Allow deleting any genre, whether user has created them or not.',
                'group' => 'genres',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:53',
                'updated_at' => '2024-04-11 19:24:53',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            78 => array(
                'id' => 79,
                'name' => 'lyrics.view',
                'display_name' => 'View Lyrics',
                'description' => 'Allow viewing and searching for lyrics.',
                'group' => 'lyrics',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:53',
                'updated_at' => '2024-04-11 19:24:53',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            79 => array(
                'id' => 80,
                'name' => 'lyrics.create',
                'display_name' => 'Create Lyrics',
                'description' => 'Allow creating new lyrics.',
                'group' => 'lyrics',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:53',
                'updated_at' => '2024-04-11 19:24:53',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            80 => array(
                'id' => 81,
                'name' => 'lyrics.update',
                'display_name' => 'Update Lyrics',
                'description' => 'Allow editing of all lyrics, whether user has created them or not.',
                'group' => 'lyrics',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:53',
                'updated_at' => '2024-04-11 19:24:53',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            81 => array(
                'id' => 82,
                'name' => 'lyrics.delete',
                'display_name' => 'Delete Lyrics',
                'description' => 'Allow deleting any lyric, whether user has created them or not.',
                'group' => 'lyrics',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:53',
                'updated_at' => '2024-04-11 19:24:53',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            82 => array(
                'id' => 83,
                'name' => 'channels.view',
                'display_name' => 'View Channels',
                'description' => 'Allow viewing channels on the site.',
                'group' => 'channels',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:53',
                'updated_at' => '2024-04-11 19:24:53',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            83 => array(
                'id' => 84,
                'name' => 'channels.create',
                'display_name' => 'Create Channels',
                'description' => 'Allow creating new channels in admin area.',
                'group' => 'channels',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:53',
                'updated_at' => '2024-04-11 19:24:53',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            84 => array(
                'id' => 85,
                'name' => 'channels.update',
                'display_name' => 'Update Channels',
                'description' => 'Allow editing of all channels in admin area.',
                'group' => 'channels',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:53',
                'updated_at' => '2024-04-11 19:24:53',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            85 => array(
                'id' => 86,
                'name' => 'channels.delete',
                'display_name' => 'Delete Channels',
                'description' => 'Allow deleting of all channels in admin area.',
                'group' => 'channels',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:53',
                'updated_at' => '2024-04-11 19:24:53',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            86 => array(
                'id' => 87,
                'name' => 'backstageRequests.view',
                'display_name' => 'View BackstageRequests',
                'description' => 'Allow viewing backstage requests.',
                'group' => 'backstage_requests',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:53',
                'updated_at' => '2024-04-11 19:24:53',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            87 => array(
                'id' => 88,
                'name' => 'backstageRequests.create',
                'display_name' => 'Create BackstageRequests',
                'description' => 'Allow creating new backstage requests.',
                'group' => 'backstage_requests',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:53',
                'updated_at' => '2024-04-11 19:24:53',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            88 => array(
                'id' => 89,
                'name' => 'backstageRequests.update',
                'display_name' => 'Update BackstageRequests',
                'description' => 'Allow editing of all backstage requests, whether user has created them or not.',
                'group' => 'backstage_requests',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:53',
                'updated_at' => '2024-04-11 19:24:53',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
            89 => array(
                'id' => 90,
                'name' => 'backstageRequests.delete',
                'display_name' => 'Delete BackstageRequests',
                'description' => 'Allow deleting any backstage request, whether user has created them or not.',
                'group' => 'backstage_requests',
                'restrictions' => NULL,
                'created_at' => '2024-04-11 19:24:53',
                'updated_at' => '2024-04-11 19:24:53',
                'type' => 'sitewide',
                'advanced' => 1,
            ),
        ]);
    }
}